apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  pern-app.yml: |
    groups:
    - name: pern-app
      rules:
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(nginx_ingress_controller_requests{service=~"backend-service|frontend-service",status=~"5.."}[5m])) /
            sum(rate(nginx_ingress_controller_requests{service=~"backend-service|frontend-service"}[5m]))
          ) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 2 minutes"
