apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patchesStrategicMerge:
  - replica-patch.yaml
  - env-patch.yaml
