apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pern-app
  namespace: argocd
spec:
  description: PERN Stack Application Project
  
  sourceRepos:
  - 'https://github.com/mankinimbom/pern-gitops'
  
  destinations:
  - namespace: 'pern-app'
    server: 'https://kubernetes.default.svc'
  - namespace: 'pern-app-staging'
    server: 'https://kubernetes.default.svc'
  - namespace: 'pern-app-production'
    server: 'https://kubernetes.default.svc'
  - namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: ClusterIssuer
  
  namespaceResourceWhitelist:
  - group: ''
    kind: Service
  - group: ''
    kind: Secret
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: PersistentVolumeClaim
  - group: ''
    kind: ServiceAccount
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: argoproj.io
    kind: Rollout
  - group: networking.k8s.io
    kind: Ingress
  - group: networking.k8s.io
    kind: NetworkPolicy
  - group: autoscaling
    kind: HorizontalPodAutoscaler
  - group: policy
    kind: PodDisruptionBudget
  - group: monitoring.coreos.com
    kind: ServiceMonitor
  - group: external-secrets.io
    kind: SecretStore
  - group: external-secrets.io
    kind: ExternalSecret
  
  roles:
  - name: admin
    description: Admin access to PERN app
    policies:
    - p, proj:pern-app:admin, applications, *, pern-app/*, allow
    - p, proj:pern-app:admin, repositories, *, *, allow
    groups:
    - argocd-admins
  
  - name: developer
    description: Developer access to PERN app
    policies:
    - p, proj:pern-app:developer, applications, get, pern-app/*, allow
    - p, proj:pern-app:developer, applications, sync, pern-app/*, allow
    groups:
    - argocd-developers
