apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd
data:
  # Global configuration
  argocd.grpc_web: "true"
  argocd.server_addr: "argocd-server.argocd.svc.cluster.local:443"
  argocd.insecure: "false"
  argocd.plaintext: "false"
  
  # Registry configuration
  registries.conf: |
    registries:
    - name: GitHub Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      credentials: pullsecret:argocd/ghcr-secret
      defaultns: library
      # Faster polling interval for GitHub Container Registry
      polling_interval: 30s
      # Enable tag sorting for better version detection
      tagsortmode: semver
      
  # Git configuration for write-back
  git.user: "argocd-image-updater[bot]"
  git.email: "argocd-image-updater@noreply.github.com"
  
  # Logging configuration
  log.level: "info"
  
  # Faster update intervals
  interval: "2m"
  health.port: "8080"
  metrics.port: "8081"
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: argocd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # Base64 encoded Docker config JSON
